###########
# site.title

title:    'EnemyUnknown Battlegrounds'
subtitle: 'A trained surviver in the harsh environment!'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
